[tool.poetry]
name = "app-python"
version = "0.1.0"
description = ""
authors = ["Ilnar Khasanov <i.khasanov@innopolis.university>"]
packages = [
    { include = "src" },
    { include = "tests" },
]

[tool.poetry.dependencies]
python = "3.12"
fastapi = "^0.109.2"
pytz = "^2024.1"
uvicorn = "^0.27.0.post1"
types-pytz = "^2024.1.0.20240203"
flake8 = "^7.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
httpx = "^0.26.0"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
black = "^24.1.1"
coverage = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
