apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      serviceAccountName: internal-app
      containers:
      - name: app-python
        image: brutaljesus/devops_lab_2:2
        ports:
        - containerPort: 8000
